# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Find and Publish the Latest HTML File
      run: |
        LATEST_HTML=$(find test-output -type f -name '*.html' -printf '%T+ %p\n' | sort -r | head -n 1 | cut -d" " -f2)
        git checkout --orphan gh-pages
        git rm -rf .
        cp $LATEST_HTML .
        git add .
        git -c user.name='GitHub Actions' -c user.email='actions@github.com' commit -m 'Publish latest HTML file'
        git push origin gh-pages --force
